#!/bin/bash

# ALIAS PACMAN
alias sps="sudo pacman -S"
alias spr="sudo pacman -Rs"
alias spu="sudo pacman -Syu"
alias orphans="sudo pacman -Rs $(pacman -Qdtq)"
alias rip="expac --timefmt='%Y-%m-%d %T' '%l\t%n' | sort | tail -100"
alias updt="sudo pacman -Syu && yay -Syu"

# ALIAS EDITORS
alias v="nvim"
alias vi="nvim"
alias vim="nvim"
alias cat="bat"

# ALIAS VARIOUS
alias shutdown="sync && sync && shutdown now"
alias reboot="sync && sync && reboot"
alias ls="exa"
alias l="exa -laG"

# ALIAS GIT
alias gs="git status"
alias gc="git commit"
alias gadd="git add ."

# ALIAS DIRECTORYS & FILES
alias cfvim="nvim ~/.config/nvim/init.vim"
alias cfzsh="nvim ~/.config/zsh/zshrc"
alias cfpacman="sudo vim /etc/pacman.conf"
alias cftmux="nvim ~/.config/tmux/tmux.conf"
alias cfalias="nvim ~/.config/zsh/aliases"
