#!/bin/sh

# Spanish keyboard layout and caps2control
riverctl keyboard-layout -options ctrl:nocaps es

# Open terminal
riverctl map normal Super+Shift Return spawn wezterm

# Close focused window
riverctl map normal Super+Shift C close

# Exit River
riverctl map normal Super+Shift E exit

# Focus next and prev window
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Swap next window
riverctl map normal Super Return swap next

# Increase decrease ratio
riverctl map normal Super+Shift Plus send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super+Shift Minus send-layout-cmd rivertile "main-ratio +0.05"

# Fullscreen
riverctl map normal Super+Shift M toggle-fullscreen

# Floating
riverctl map normal Super F toggle-float

# Multiple monitors
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Resizing
riverctl map normal Super+Shift H resize horizontal -100
riverctl map normal Super+Shift J resize vertical 100
riverctl map normal Super+Shift K resize vertical -100
riverctl map normal Super+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Dmenu
riverctl map normal Super P spawn "dmenu_run -fn 'Iosevka Nerd Font-14' -nb '#191919' -nf '#ececec' -sb '#ececec' -sf '#191919'"

# Styling
riverctl background-color 0x121212
riverctl border-color-focused 0xececec
riverctl border-color-unfocused 0x191919

gsettings set org.gnome.desktop.interface gtk-theme "Breeze-Dark"
gsettings set org.gnome.desktop.interface icon-theme "Breeze Dark"

# Focus follows cursor
riverctl focus-follows-cursor normal

# Tags
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags
done

# Volume
for mode in normal locked
do
    riverctl map -repeat $mode None XF86AudioLowerVolume spawn "pamixer -d 5"
    riverctl map -repeat $mode None XF86AudioRaiseVolume spawn "pamixer -i 5"
done

# Notifications
mako &
riverctl map normal Super Escape spawn "makoctl dismiss"

# Displays
kanshi &

# Bar
waybar &

# Default layout
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &
