# ENV VARIABLES
export ZSH="/home/samuel/.oh-my-zsh"
export EDITOR="/usr/bin/nvim"
export BROWSER="brave"
export PATH=$PATH:~/.local/bin:~/.yarn/bin/
export GOPATH=$HOME/.go

# THEME
ZSH_THEME="arrow"

# OH MY ZSH
source $ZSH/oh-my-zsh.sh

# PLUGINS
plugins=(git)
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# ALIASES
source ~/.config/zsh/aliases

# FNM
eval "$(fnm env)"

# TMUX
[[ $TERM != "screen" ]] && exec tmux -f ~/.config/tmux/tmux.conf
