#!/usr/bin/env bash

### USER ENV VARIALBES ###
export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit
export JAVA_HOME=/usr/lib/jvm/default
wmname LG3D &

### FIX TOUCHPAD ISSUES (TEMP WORKAROUND) ###
rmmod i2c_hid_acpi &
modprobe i2c_hid_acpi &

### DISABLE PC SPEAKER ###
rmmod pcspkr &

### COMPOSITOR ###
picom --backend glx --no-fading-openclose &

### WALLPAPER ###
nitrogen --restore &

### MULTIMONITOR SETUP ###
xrandr --output eDP --primary --mode 1920x1080 --pos -1920x0 --rotate normal --output HDMI-A-0 --mode 1920x1080 --pos 0x0 --rotate normal &

### KEYBOARD ###
setxkbmap es &

### APPLETS ###
nm-applet &
pasystray &
cbatticon &

### DWMBLOCKS ###
dwmblocks &
