eval "$(/opt/homebrew/bin/brew shellenv)"
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"


# Added by Toolbox App
export PATH="$PATH:/Users/samuel/Library/Application Support/JetBrains/Toolbox/scripts"