export ANDROID_HOME=/Users/samuel/Library/Android/sdk
export PATH=/Users/samuel/Library/Android/sdk/platform-tools:$PATH
. "$HOME/.cargo/env"

__conda_setup="$('/Users/samuel/.miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/samuel/.miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/samuel/.miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/samuel/.miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup

export DENO_INSTALL="/Users/samuel/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"
