# ENV VARIABLES
export ZSH="$HOME/.oh-my-zsh"
export EDITOR="/opt/homebrew/bin/nvim"
export PATH=$PATH:~/.local/bin:~/.yarn/bin/:/usr/local/
export GOPATH=$HOME/.go
export PROMPT_EOL_MARK=''
export DOTNET_CLI_TELEMETRY_OPTOUT=1

# THEME
ZSH_THEME="arrow"

# OH MY ZSH
source $ZSH/oh-my-zsh.sh

# PLUGINS
plugins=(git)
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# ALIASES
source ~/.config/zsh/aliases

# FNM
eval "$(fnm env --use-on-cd)"

# THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# SYNTAX HIGHLIGHTING COLORS
ZSH_HIGHLIGHT_STYLES[suffix-alias]=fg=blue,underline
ZSH_HIGHLIGHT_STYLES[precommand]=fg=blue,underline
ZSH_HIGHLIGHT_STYLES[arg0]=fg=blue
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#787878"

# OPAM
[[ ! -r /Users/samuel/.opam/opam-init/init.zsh ]] || source /Users/samuel/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null

# DOCKER-DESKTOP
# source /Users/samuel/.docker/init-zsh.sh || true # Added by Docker Desktop

# RBENV
eval "$(rbenv init - zsh)"

# GOTO
goto() {
	cd $(find /Users/samuel/Code /Users/samuel/Desktop /Users/samuel/Documents /Users/samuel/Downloads /Users/samuel/Repos /Users/samuel/.config /Users/samuel/.local -type d -maxdepth 5 -mindepth 1 | fzf)
}
